### ISSUE TITLE
GET /feeds lastPostId 보다 작은 5 개의 인스타그램 피드 조회 가 이상해요

### ISSUE THREAD

**Issue by sangdo913** [INSPJT/instagram_clone_backend#112]
# Bug
 **전송** : https://codevpros.com/feeds?lastPostId=1 (81ms)

라스트포스트가 1인데 id가 2인애도 있고 15인애도 있고 이상합니다!
last도 false가 나왔어요!!
그리고 최신순으로 내림차순이어야하는데 오름차순으로 나와요!

**받은 값**
I/okhttp.OkHttpClient: {"content":[{"id":1,"author":{"displayId":"Aos","profileImageUrl":null,"isFollowedByMe":true},"createdAt":"2021-06-15 13:16:11","modifiedAt":"2021-06-19 19:29:34","isLike":true,"commentPreview":[{"id":1,"author":{"displayId":"Aos1","profileImageUrl":null,"isFollowedByMe":false},"isLike":false,"created":"2021-06-19T16:19:33.736306","content":"string","likeLength":0}],"viewCount":0,"images":["https://drive.google.com/uc?export=view&id=1RzMaWvss5AGQRRj8TAIPlvw4egWZ2J77"],"body":"test","likeUser":{"displayId":"Aos1","profileImageUrl":null,"isFollowedByMe":false},"likeLength":2,"commentLength":1},{"id":2,"author":{"displayId":"Aos","profileImageUrl":null,"isFollowedByMe":true},"createdAt":"2021-06-15 13:19:58","modifiedAt":"2021-06-15 13:19:58","isLike":false,"commentPreview":[],"viewCount":0,"images":["https://drive.google.com/uc?export=view&id=1LW3mwzZR3V7064qcA2lceO7EWQ1rnYE0","https://drive.google.com/uc?export=view&id=13IvrL3v-B5pYITerU9uRH_KNJmTKUEYe"],"body":"test","likeUser":null,"likeLength":0,"commentLength":0},{"id":3,"author":{"displayId":"Aos","profileImageUrl":null,"isFollowedByMe":true},"createdAt":"2021-06-15 13:26:21","modifiedAt":"2021-06-15 13:26:21","isLike":false,"commentPreview":[],"viewCount":0,"images":["https://drive.google.com/uc?export=view&id=17o906lWvoO9zBqBW-ouKWs3wE2XUhmct","https://drive.google.com/uc?export=view&id=16MhBNt5gwUb28qXjNC9Le3Q9_3bEwFgI","https://drive.google.com/uc?export=view&id=1_RbL7E9NkxjqsDkOiA3Ntb10jzBXarJl","https://drive.google.com/uc?export=view&id=1iECj7qGNDVtwEvkwfLQgG2qnCr4lLOWn","https://drive.google.com/uc?export=view&id=1ZO9ex7J5S83ezFPhMnPpwcCnTplv6gvh","https://drive.google.com/uc?export=view&id=1EY8Tqlk2fU3gqAw8J76oAOBcI4M5MiQB","https://drive.google.com/uc?export=view&id=1k6zd2O0OlDJ17JoxOKCr9KDBkZ5UETkO"],"body":"test","likeUser":null,"likeLength":0,"commentLength":0},{"id":4,"author":{"displayId":"Aos","profileImageUrl":null,"isFollowedByMe":true},"createdAt":"2021-06-15 23:51:46","modifiedAt":"2021-06-15 23:51:46","isLike":false,"commentPreview":[],"viewCount":0,"images":["https://drive.google.com/uc?export=view&id=1uhiqPInvdmz9kkGR3tJZCtBeQOcZAX9Y"],"body":"test","likeUser":null,"likeLength":0,"commentLength":0},{"id":5,"author":{"displayId":"Aos","profileImageUrl":null,"isFollowedByMe":true},"createdAt":"2021-06-15 23:54:59","modifiedAt":"2021-06-15 23:54:59","isLike":false,"commentPreview":[],"viewCount":0,"images":["https://drive.google.com/uc?export=view&id=1NXdJRn8lxHNdBUj6i5usf6n1YwKTtjQ3","https://drive.google.com/uc?export=view&id=1q8qkqFkQ-Gz0vhhCRpItIdqaYgwAuNiF","https://drive.google.com/uc?export=view&id=1nAGDjHZSC61dTRRdfX0JqBidcv-LHf_h"],"body":"test","likeUser":null,"likeLength":0,"commentLength":0},{"id":6,"author":{"displayId":"Aos","profileImageUrl":null,"isFollowedByMe":true},"createdAt":"2021-06-15 23:55:24","modifiedAt":"2021-06-15 23:55:24","isLike":false,"commentPreview":[],"viewCount":0,"images":["https://drive.google.com/uc?export=view&id=1iG7aoGCtNmeA-UuSmBvXaejXs5tYPvX9"],"body":"test","likeUser":null,"likeLength":0,"commentLength":0},{"id":8,"author":{"displayId":"Aos","profileImageUrl":null,"isFollowedByMe":true},"createdAt":"2021-06-17 12:39:51","modifiedAt":"2021-06-17 12:39:51","isLike":false,"commentPreview":[],"viewCount":0,"images":[],"body":"test","likeUser":null,"likeLength":0,"commentLength":0},{"id":9,"author":{"displayId":"Aos","profileImageUrl":null,"isFollowedByMe":true},"createdAt":"2021-06-17 12:42:21","modifiedAt":"2021-06-17 12:42:21","isLike":false,"commentPreview":[],"viewCount":0,"images":[],"body":"test","likeUser":null,"likeLength":0,"commentLength":0},{"id":10,"author":{"displayId":"Aos","profileImageUrl":null,"isFollowedByMe":true},"createdAt":"2021-06-17 12:45:53","modifiedAt":"2021-06-17 12:45:53","isLike":false,"commentPreview":[],"viewCount":0,"images":[],"body":"test","likeUser":null,"likeLength":0,"commentLength":0},{"id":11,"author":{"displayId":"Aos","profileImageUrl":null,"isFollowedByMe":true},"created
    At":"2021-06-17 12:49:04","modifiedAt":"2021-06-17 12:49:04","isLike":false,"commentPreview":[],"viewCount":0,"images":[],"body":"test","likeUser":null,"likeLength":0,"commentLength":0},{"id":12,"author":{"displayId":"Aos","profileImageUrl":null,"isFollowedByMe":true},"createdAt":"2021-06-17 12:49:05","modifiedAt":"2021-06-17 12:49:05","isLike":false,"commentPreview":[],"viewCount":0,"images":[],"body":"test","likeUser":null,"likeLength":0,"commentLength":0},{"id":13,"author":{"displayId":"Aos","profileImageUrl":null,"isFollowedByMe":true},"createdAt":"2021-06-17 12:50:05","modifiedAt":"2021-06-17 12:50:05","isLike":false,"commentPreview":[],"viewCount":0,"images":[],"body":"test","likeUser":null,"likeLength":0,"commentLength":0},{"id":15,"author":{"displayId":"Aos","profileImageUrl":null,"isFollowedByMe":true},"createdAt":"2021-06-17 14:00:05","modifiedAt":"2021-06-17 14:00:05","isLike":false,"commentPreview":[],"viewCount":0,"images":["https://yurivongella.s3.ap-northeast-2.amazonaws.com/MEMBER/3/1623938404986-201603211108-Reissue-pet-family-01.jpg"],"body":"test","likeUser":null,"likeLength":0,"commentLength":0},{"id":16,"author":{"displayId":"Aos","profileImageUrl":null,"isFollowedByMe":true},"createdAt":"2021-06-17 14:01:26","modifiedAt":"2021-06-17 14:01:26","isLike":false,"commentPreview":[],"viewCount":0,"images":["https://yurivongella.s3.ap-northeast-2.amazonaws.com/MEMBER/3/1623938485252-%EB%8B%A4%EC%9A%B4%EB%A1%9C%EB%93%9C.jpg","https://yurivongella.s3.ap-northeast-2.amazonaws.com/MEMBER/3/1623938485593-201603211108-Reissue-pet-family-01.jpg","https://yurivongella.s3.ap-northeast-2.amazonaws.com/MEMBER/3/1623938485651-2018011700908_0.jpg","https://yurivongella.s3.ap-northeast-2.amazonaws.com/MEMBER/3/1623938485843-00501921_20191015.jpg"],"body":"test","likeUser":null,"likeLength":0,"commentLength":0},{"id":17,"author":{"displayId":"Aos","profileImageUrl":null,"isFollowedByMe":true},"createdAt":"2021-06-17 14:02:08","modifiedAt":"2021-06-17 14:02:08","isLike":false,"commentPreview":[],"viewCount":0,"images":["https://yurivongella.s3.ap-northeast-2.amazonaws.com/MEMBER/3/1623938528308-2018011700908_0.jpg","https://yurivongella.s3.ap-northeast-2.amazonaws.com/MEMBER/3/1623938528540-IMG_20200624_133341.jpg"],"body":"test","likeUser":null,"likeLength":0,"commentLength":0},{"id":18,"author":{"displayId":"Aos","profileImageUrl":null,"isFollowedByMe":true},"createdAt":"2021-06-17 14:02:24","modifiedAt":"2021-06-17 14:02:24","isLike":false,"commentPreview":[],"viewCount":0,"images":["https://yurivongella.s3.ap-northeast-2.amazonaws.com/MEMBER/3/1623938543785-00501921_20191015.jpg","https://yurivongella.s3.ap-northeast-2.amazonaws.com/MEMBER/3/1623938543878-_104444203_d03fb5eb-685c-42c3-8fa2-eea0ee2dac26.jpg","https://yurivongella.s3.ap-northeast-2.amazonaws.com/MEMBER/3/1623938544237-201603211108-Reissue-pet-family-01.jpg","https://yurivongella.s3.ap-northeast-2.amazonaws.com/MEMBER/3/1623938544304-2018011700908_0.jpg"],"body":"test","likeUser":null,"likeLength":0,"commentLength":0},{"id":19,"author":{"displayId":"Aos","profileImageUrl":null,"isFollowedByMe":true},"createdAt":"2021-06-17 14:14:25","modifiedAt":"2021-06-17 14:14:25","isLike":false,"commentPreview":[],"viewCount":0,"images":["https://yurivongella.s3.ap-northeast-2.amazonaws.com/MEMBER/3/1623939264754-%EB%8B%A4%EC%9A%B4%EB%A1%9C%EB%93%9C.jpg","https://yurivongella.s3.ap-northeast-2.amazonaws.com/MEMBER/3/1623939264971-201603211108-Reissue-pet-family-01.jpg"],"body":"test","likeUser":null,"likeLength":0,"commentLength":0},{"id":20,"author":{"displayId":"Aos","profileImageUrl":null,"isFollowedByMe":true},"createdAt":"2021-06-19 11:43:13","modifiedAt":"2021-06-19 11:43:13","isLike":false,"commentPreview":[],"viewCount":0,"images":["https://yurivongella.s3.ap-northeast-2.amazonaws.com/MEMBER/3/1624102992516-201603211108-Reissue-pet-family-01.jpg"],"body":"test","likeUser":null,"likeLength":0,"commentLength":0},{"id":21,"author":{"displayId":"Aos","profileImageUrl":
    null,"isFollowedByMe":true},"createdAt":"2021-06-19 11:43:17","modifiedAt":"2021-06-19 11:43:17","isLike":false,"commentPreview":[],"viewCount":0,"images":["https://yurivongella.s3.ap-northeast-2.amazonaws.com/MEMBER/3/1624102997500-IMG_20200624_133341.jpg"],"body":"test","likeUser":null,"likeLength":0,"commentLength":0},{"id":22,"author":{"displayId":"Aos","profileImageUrl":null,"isFollowedByMe":true},"createdAt":"2021-06-19 12:51:28","modifiedAt":"2021-06-19 12:51:28","isLike":false,"commentPreview":[],"viewCount":0,"images":["https://yurivongella.s3.ap-northeast-2.amazonaws.com/MEMBER/3/1624107087241-%EB%8B%A4%EC%9A%B4%EB%A1%9C%EB%93%9C.jpg","https://yurivongella.s3.ap-northeast-2.amazonaws.com/MEMBER/3/1624107087590-_104444203_d03fb5eb-685c-42c3-8fa2-eea0ee2dac26.jpg","https://yurivongella.s3.ap-northeast-2.amazonaws.com/MEMBER/3/1624107087741-201603211108-Reissue-pet-family-01.jpg","https://yurivongella.s3.ap-northeast-2.amazonaws.com/MEMBER/3/1624107087970-2018011700908_0.jpg","https://yurivongella.s3.ap-northeast-2.amazonaws.com/MEMBER/3/1624107088028-00501921_20191015.jpg"],"body":"test","likeUser":null,"likeLength":0,"commentLength":0}],"pageable":{"sort":{"sorted":false,"unsorted":true,"empty":true},"offset":0,"pageNumber":0,"pageSize":20,"paged":true,"unpaged":false},"size":20,"number":0,"sort":{"sorted":false,"unsorted":true,"empty":true},"numberOfElements":20,"first":true,"last":false,"empty":false}
    <-- END HTTP (9435-byte body)
E/SD: last : false

# How to fix (suggest)
- 1. 피드 id가 내림차순으로 나오게 해주세요!
- 2. lastPostId 미만인 값들만 조회되게 해주세요!

# Assignee
- 감사합니다.

**Comment by DolphaGo** [comment]
너모 귀여워요 얼른 고쳐주고 싶어요

**Comment by DolphaGo** [comment]
`lastPostId` 말고 `offset` 이라는 이름으로 할게요. 다른 도메인들에서도 공통적으로 offset이라는 이름을 사용하는 것이 좋겠어요!

**Comment by ParkJiwoon** [comment]
> `lastPostId` 말고 `offset` 이라는 이름으로 할게요. 다른 도메인들에서도 공통적으로 offset이라는 이름을 사용하는 것이 좋겠어요!

Pageable 의 offset 과 헷갈리진 않을까요

**Comment by DolphaGo** [comment]
내부 구현이 잘못 됐을 가능성이 높아보여요.
`Pageable`은 정말 많이 사용하는 것이라서 미숙함에 의한 것 같아서 좀 만 더 살펴볼게여!

**Comment by DolphaGo** [comment]
우선 팬텀리드는 없다고 가정하고 아까전에 논의했던 offset으로만 가져오는 식으로
그리고 요구사항이 다들 최신인 것 같아서, 댓글도, 포스트도 모두 최신 먼저 내려주는 것으로 하져!

**Comment by DolphaGo** [comment]
@ParkJiwoon `page=?&size=?`
offset은 query 용어네요 ㅋㅋ

page => offset
size => limit
