### ISSUE TITLE
프로젝트 구조 리팩토링 ?

### ISSUE THREAD

**Issue by ParkJiwoon** [INSPJT/instagram_clone_backend#113]
# Feature
- 처음에 너무 아무 생각없이 짜다보니 `dto` 디렉토리 하위도 제대로 정리 안되어있고 도메인도 정리 안되어있는거 같아서 정리 필요
- 도메인 변경 ?
  - ~`follow` 액션이 `MemberController` 에 들어가있는데 `FollowController` 를 따로 분리하는게 좋아보임~
    - ~`FollowController`: 사용자 팔로우, 언팔로우 액션~
    - `MemberController`: 사용자 정보 변경에 관한 내용 (Profile 과 통일할 수 잇을 것 같음)
  - 그리고 응답을 Post 로 내려주는 API 가 많은데 (/profiles, /posts/ feeds 등등..) 하나로 통일할 수 있지 않을까?
    - 지금 /feeds 의 응답은 `commentPreview` 필드가 내려가구 있는데 #110 와 같은 의견으로 없앨 수 있을 것 같음
    - 그럼 결국 Post 내려주는 응답은 하나로 통일할 수 있을 것 같은데 너무 컨트롤러 여기저기에 흩어져 있는 느낌

# Assignees
- @ParkJiwoon

**Comment by ParkJiwoon** [comment]
@syureu 의 추가 의견

- 지금 프로젝트 구조가 domain 도 아니고 layered 도 아닌 애매한 상태인데 하나로 통일하는게 좋지않을까?
- mode, repo 만 도메인 형태고 나머지는 레이어드인데 둘중 하나로 확실히 하는게 좋아보임

**Comment by ParkJiwoon** [comment]
@DolphaGo @syureu @AndoneKwon @heonilp 

한번 읽어보구 의견 주면 좋을 것 같습니다.

**Comment by AndoneKwon** [comment]
도메인 변경 사항과 DTO 정리에 
하지만 피드 같은경우에는
"한 멤버의 Post 게시물에만 접근하는 것이 아닌 Follow 정보에 대해서도 접근해야 한다."
라는 이유 때문에 성격이 조금 다르지 않나요?

**Comment by ParkJiwoon** [comment]
> 도메인 변경 사항과 DTO 정리에
> 하지만 피드 같은경우에는
> "한 멤버의 Post 게시물에만 접근하는 것이 아닌 Follow 정보에 대해서도 접근해야 한다."
> 라는 이유 때문에 성격이 조금 다르지 않나요?

사실 조금씩 다 다르긴 해요

- `post`: post 만 조회
- `profile`: member 와 post 조회
- `feed`: member 와 follow, post 조회

그런데 결국 서버 입장에서 member, follow 는 부가적인 요인이지 post 가 메인 리소스라고 생각되어서 한 서비스에 묶으려고 했는데요
필요하다면 DTO 정도만 최대한 통일하고 다 각각의 Service 로 분리해도 될거같네요

**Comment by AndoneKwon** [comment]
> > 도메인 변경 사항과 DTO 정리에
> > 하지만 피드 같은경우에는
> > "한 멤버의 Post 게시물에만 접근하는 것이 아닌 Follow 정보에 대해서도 접근해야 한다."
> > 라는 이유 때문에 성격이 조금 다르지 않나요?
> 
> 사실 조금씩 다 다르긴 해요
> 
> * `post`: post 만 조회
> * `profile`: member 와 post 조회
> * `feed`: member 와 follow, post 조회
> 
> 그런데 결국 서버 입장에서 member, follow 는 부가적인 요인이지 post 가 메인 리소스라고 생각되어서 한 서비스에 묶으려고 했는데요
> 필요하다면 DTO 정도만 최대한 통일하고 다 각각의 Service 로 분리해도 될거같네요

전 중앙님이 하시는데로 따르겠습니다..!

**Comment by ParkJiwoon** [comment]
변경하기로 결정했으므로 이 이슈는 닫고 별개 이슈로 따겠습니다
