### ISSUE TITLE
단순 질문입니다. (feed)

### ISSUE THREAD

**Issue by sangdo913** [INSPJT/instagram_clone_backend#126]
**질문**
피드 질문입니다.
AOS로 로그인한 뒤에 피드를 받을 때, 피드에서 자기 자신에 대한 게시물을 받는게 맞나요??
뭔가 자기 자신 게시물은 안와도 될 것 같은 느낌적인 느낌입니다.

**스웨거 로그**
{
  "hasNext": true,
  "posts": [
    {
      "id": 29,
      "content": "test",
      "author": {
        "displayId": "Aos",   <-- Aos로 로그인 했는데 Aos 글이 왔습니다.
        "nickname": "Aos",
        "profileImageUrl": null,
        "introduction": null,
        "postCount": 15,
        "followingCount": 1,
        "followerCount": 1,
        "isFollowedByMe": false
      },
      "mediaUrls": [
        {
          "mediaUrlId": 46,
          "url": "https://yurivongella.s3.ap-northeast-2.amazonaws.com/MEMBER/3/1624535532342-IMG_20200624_133341.jpg",
          "type": "IMAGE"
        },
        {
          "mediaUrlId": 47,
          "url": "https://yurivongella.s3.ap-northeast-2.amazonaws.com/MEMBER/3/1624535532196-00501921_20191015.jpg",
          "type": "IMAGE"
        },
        {
          "mediaUrlId": 48,
          "url": "https://yurivongella.s3.ap-northeast-2.amazonaws.com/MEMBER/3/1624535531884-%EB%8B%A4%EC%9A%B4%EB%A1%9C%EB%93%9C.jpg",
          "type": "IMAGE"
        },
        {
          "mediaUrlId": 49,
          "url": "https://yurivongella.s3.ap-northeast-2.amazonaws.com/MEMBER/3/1624535531978-_104444203_d03fb5eb-685c-42c3-8fa2-eea0ee2dac26.jpg",
          "type": "IMAGE"
        },
        {
          "mediaUrlId": 50,
          "url": "https://yurivongella.s3.ap-northeast-2.amazonaws.com/MEMBER/3/1624535532145-2018011700908_0.jpg",
          "type": "IMAGE"
        },
        {
          "mediaUrlId": 51,
          "url": "https://yurivongella.s3.ap-northeast-2.amazonaws.com/MEMBER/3/1624535533042-201603211108-Reissue-pet-family-01.jpg",
          "type": "IMAGE"
        },
        {
          "mediaUrlId": 52,
          "url": "https://yurivongella.s3.ap-northeast-2.amazonaws.com/MEMBER/3/1624535533147-IMG_20200624_133334.jpg",
          "type": "IMAGE"
        }
      ],
      "isLike": false,
      "likeCount": 0,
      "commentCount": 0,
      "viewCount": 0,
      "createdDate": "2021-06-24 11:52:13",
      "modifiedDate": "2021-06-24 11:52:13"
    },
    {
      "id": 23,
      "content": "test",
      "author": {
        "displayId": "Aos",
        "nickname": "Aos",
        "profileImageUrl": null,
        "introduction": null,
        "postCount": 15,
        "followingCount": 1,
        "followerCount": 1,
        "isFollowedByMe": false
      },
      "mediaUrls": [
        {
          "mediaUrlId": 38,
          "url": "https://yurivongella.s3.ap-northeast-2.amazonaws.com/MEMBER/3/1624107135739-%EB%8B%A4%EC%9A%B4%EB%A1%9C%EB%93%9C.jpg",
          "type": "IMAGE"
        },
        {
          "mediaUrlId": 39,
          "url": "https://yurivongella.s3.ap-northeast-2.amazonaws.com/MEMBER/3/1624107136083-201603211108-Reissue-pet-family-01.jpg",
          "type": "IMAGE"
        },
        {
          "mediaUrlId": 40,
          "url": "https://yurivongella.s3.ap-northeast-2.amazonaws.com/MEMBER/3/1624107136127-2018011700908_0.jpg",
          "type": "IMAGE"
        }
      ],
      "isLike": false,
      "likeCount": 0,
      "commentCount": 0,
      "viewCount": 0,
      "createdDate": "2021-06-19 12:52:16",
      "modifiedDate": "2021-06-19 12:52:16"
    },
    {
      "id": 22,
      "content": "test",
      "author": {
        "displayId": "Aos",
        "nickname": "Aos",
        "profileImageUrl": null,
        "introduction": null,
        "postCount": 15,
        "followingCount": 1,
        "followerCount": 1,
        "isFollowedByMe": false
      },
      "mediaUrls": [
        {
          "mediaUrlId": 33,
          "url": "https://yurivongella.s3.ap-northeast-2.amazonaws.com/MEMBER/3/1624107087241-%EB%8B%A4%EC%9A%B4%EB%A1%9C%EB%93%9C.jpg",
          "type": "IMAGE"
        },
        {
          "mediaUrlId": 34,
          "url": "https://yurivongella.s3.ap-northeast-2.amazonaws.com/MEMBER/3/1624107087590-_104444203_d03fb5eb-685c-42c3-8fa2-eea0ee2dac26.jpg",
          "type": "IMAGE"
        },
        {
          "mediaUrlId": 35,
          "url": "https://yurivongella.s3.ap-northeast-2.amazonaws.com/MEMBER/3/1624107087741-201603211108-Reissue-pet-family-01.jpg",
          "type": "IMAGE"
        },
        {
          "mediaUrlId": 36,
          "url": "https://yurivongella.s3.ap-northeast-2.amazonaws.com/MEMBER/3/1624107087970-2018011700908_0.jpg",
          "type": "IMAGE"
        },
        {
          "mediaUrlId": 37,
          "url": "https://yurivongella.s3.ap-northeast-2.amazonaws.com/MEMBER/3/1624107088028-00501921_20191015.jpg",
          "type": "IMAGE"
        }
      ],
      "isLike": false,
      "likeCount": 0,
      "commentCount": 0,
      "viewCount": 0,
      "createdDate": "2021-06-19 12:51:28",
      "modifiedDate": "2021-06-19 12:51:28"
    },
    {
      "id": 21,
      "content": "test",
      "author": {
        "displayId": "Aos",
        "nickname": "Aos",
        "profileImageUrl": null,
        "introduction": null,
        "postCount": 15,
        "followingCount": 1,
        "followerCount": 1,
        "isFollowedByMe": false
      },
      "mediaUrls": [
        {
          "mediaUrlId": 32,
          "url": "https://yurivongella.s3.ap-northeast-2.amazonaws.com/MEMBER/3/1624102997500-IMG_20200624_133341.jpg",
          "type": "IMAGE"
        }
      ],
      "isLike": false,
      "likeCount": 0,
      "commentCount": 0,
      "viewCount": 0,
      "createdDate": "2021-06-19 11:43:17",
      "modifiedDate": "2021-06-19 11:43:17"
    },
    {
      "id": 20,
      "content": "test",
      "author": {
        "displayId": "Aos",
        "nickname": "Aos",
        "profileImageUrl": null,
        "introduction": null,
        "postCount": 15,
        "followingCount": 1,
        "followerCount": 1,
        "isFollowedByMe": false
      },
      "mediaUrls": [
        {
          "mediaUrlId": 31,
          "url": "https://yurivongella.s3.ap-northeast-2.amazonaws.com/MEMBER/3/1624102992516-201603211108-Reissue-pet-family-01.jpg",
          "type": "IMAGE"
        }
      ],
      "isLike": false,
      "likeCount": 0,
      "commentCount": 0,
      "viewCount": 0,
      "createdDate": "2021-06-19 11:43:13",
      "modifiedDate": "2021-06-19 11:43:13"
    },
    {
      "id": 18,
      "content": "test",
      "author": {
        "displayId": "Aos",
        "nickname": "Aos",
        "profileImageUrl": null,
        "introduction": null,
        "postCount": 15,
        "followingCount": 1,
        "followerCount": 1,
        "isFollowedByMe": false
      },
      "mediaUrls": [
        {
          "mediaUrlId": 25,
          "url": "https://yurivongella.s3.ap-northeast-2.amazonaws.com/MEMBER/3/1623938543785-00501921_20191015.jpg",
          "type": "IMAGE"
        },
        {
          "mediaUrlId": 26,
          "url": "https://yurivongella.s3.ap-northeast-2.amazonaws.com/MEMBER/3/1623938543878-_104444203_d03fb5eb-685c-42c3-8fa2-eea0ee2dac26.jpg",
          "type": "IMAGE"
        },
        {
          "mediaUrlId": 27,
          "url": "https://yurivongella.s3.ap-northeast-2.amazonaws.com/MEMBER/3/1623938544237-201603211108-Reissue-pet-family-01.jpg",
          "type": "IMAGE"
        },
        {
          "mediaUrlId": 28,
          "url": "https://yurivongella.s3.ap-northeast-2.amazonaws.com/MEMBER/3/1623938544304-2018011700908_0.jpg",
          "type": "IMAGE"
        }
      ],
      "isLike": false,
      "likeCount": 0,
      "commentCount": 0,
      "viewCount": 0,
      "createdDate": "2021-06-17 14:02:24",
      "modifiedDate": "2021-06-17 14:02:24"
    },
    {
      "id": 17,
      "content": "test",
      "author": {
        "displayId": "Aos",
        "nickname": "Aos",
        "profileImageUrl": null,
        "introduction": null,
        "postCount": 15,
        "followingCount": 1,
        "followerCount": 1,
        "isFollowedByMe": false
      },
      "mediaUrls": [
        {
          "mediaUrlId": 23,
          "url": "https://yurivongella.s3.ap-northeast-2.amazonaws.com/MEMBER/3/1623938528308-2018011700908_0.jpg",
          "type": "IMAGE"
        },
        {
          "mediaUrlId": 24,
          "url": "https://yurivongella.s3.ap-northeast-2.amazonaws.com/MEMBER/3/1623938528540-IMG_20200624_133341.jpg",
          "type": "IMAGE"
        }
      ],
      "isLike": false,
      "likeCount": 0,
      "commentCount": 0,
      "viewCount": 0,
      "createdDate": "2021-06-17 14:02:08",
      "modifiedDate": "2021-06-17 14:02:08"
    },
    {
      "id": 16,
      "content": "test",
      "author": {
        "displayId": "Aos",
        "nickname": "Aos",
        "profileImageUrl": null,
        "introduction": null,
        "postCount": 15,
        "followingCount": 1,
        "followerCount": 1,
        "isFollowedByMe": false
      },
      "mediaUrls": [
        {
          "mediaUrlId": 19,
          "url": "https://yurivongella.s3.ap-northeast-2.amazonaws.com/MEMBER/3/1623938485252-%EB%8B%A4%EC%9A%B4%EB%A1%9C%EB%93%9C.jpg",
          "type": "IMAGE"
        },
        {
          "mediaUrlId": 20,
          "url": "https://yurivongella.s3.ap-northeast-2.amazonaws.com/MEMBER/3/1623938485593-201603211108-Reissue-pet-family-01.jpg",
          "type": "IMAGE"
        },
        {
          "mediaUrlId": 21,
          "url": "https://yurivongella.s3.ap-northeast-2.amazonaws.com/MEMBER/3/1623938485651-2018011700908_0.jpg",
          "type": "IMAGE"
        },
        {
          "mediaUrlId": 22,
          "url": "https://yurivongella.s3.ap-northeast-2.amazonaws.com/MEMBER/3/1623938485843-00501921_20191015.jpg",
          "type": "IMAGE"
        }
      ],
      "isLike": false,
      "likeCount": 0,
      "commentCount": 0,
      "viewCount": 0,
      "createdDate": "2021-06-17 14:01:26",
      "modifiedDate": "2021-06-17 14:01:26"
    },
    {
      "id": 15,
      "content": "test",
      "author": {
        "displayId": "Aos",
        "nickname": "Aos",
        "profileImageUrl": null,
        "introduction": null,
        "postCount": 15,
        "followingCount": 1,
        "followerCount": 1,
        "isFollowedByMe": false
      },
      "mediaUrls": [
        {
          "mediaUrlId": 18,
          "url": "https://yurivongella.s3.ap-northeast-2.amazonaws.com/MEMBER/3/1623938404986-201603211108-Reissue-pet-family-01.jpg",
          "type": "IMAGE"
        }
      ],
      "isLike": false,
      "likeCount": 0,
      "commentCount": 0,
      "viewCount": 0,
      "createdDate": "2021-06-17 14:00:05",
      "modifiedDate": "2021-06-17 14:00:05"
    },
    {
      "id": 7,
      "content": "test",
      "author": {
        "displayId": "Aos1",
        "nickname": "Aos1",
        "profileImageUrl": null,
        "introduction": null,
        "postCount": 1,
        "followingCount": 1,
        "followerCount": 1,
        "isFollowedByMe": true
      },
      "mediaUrls": [
        {
          "mediaUrlId": 16,
          "url": "https://drive.google.com/uc?export=view&id=1oQl4F8DUmbLfBmaYQpGwSFq_PJh1qLt4",
          "type": "VIDEO"
        }
      ],
      "isLike": false,
      "likeCount": 0,
      "commentCount": 0,
      "viewCount": 0,
      "createdDate": "2021-06-16 00:07:27",
      "modifiedDate": "2021-06-16 00:07:27"
    },
    {
      "id": 6,
      "content": "test",
      "author": {
        "displayId": "Aos",
        "nickname": "Aos",
        "profileImageUrl": null,
        "introduction": null,
        "postCount": 15,
        "followingCount": 1,
        "followerCount": 1,
        "isFollowedByMe": false
      },
      "mediaUrls": [
        {
          "mediaUrlId": 15,
          "url": "https://drive.google.com/uc?export=view&id=1iG7aoGCtNmeA-UuSmBvXaejXs5tYPvX9",
          "type": "VIDEO"
        }
      ],
      "isLike": false,
      "likeCount": 0,
      "commentCount": 0,
      "viewCount": 0,
      "createdDate": "2021-06-15 23:55:24",
      "modifiedDate": "2021-06-15 23:55:24"
    },
    {
      "id": 5,
      "content": "test",
      "author": {
        "displayId": "Aos",
        "nickname": "Aos",
        "profileImageUrl": null,
        "introduction": null,
        "postCount": 15,
        "followingCount": 1,
        "followerCount": 1,
        "isFollowedByMe": false
      },
      "mediaUrls": [
        {
          "mediaUrlId": 12,
          "url": "https://drive.google.com/uc?export=view&id=1NXdJRn8lxHNdBUj6i5usf6n1YwKTtjQ3",
          "type": "VIDEO"
        },
        {
          "mediaUrlId": 13,
          "url": "https://drive.google.com/uc?export=view&id=1q8qkqFkQ-Gz0vhhCRpItIdqaYgwAuNiF",
          "type": "VIDEO"
        },
        {
          "mediaUrlId": 14,
          "url": "https://drive.google.com/uc?export=view&id=1nAGDjHZSC61dTRRdfX0JqBidcv-LHf_h",
          "type": "VIDEO"
        }
      ],
      "isLike": false,
      "likeCount": 0,
      "commentCount": 0,
      "viewCount": 0,
      "createdDate": "2021-06-15 23:54:59",
      "modifiedDate": "2021-06-15 23:54:59"
    }
  ]
}

**Comment by ParkJiwoon** [comment]
인스타 피드에서 본인이 작성한 글도 보인다고 해서 피드 대상에 추가했었습니다.
제가 글을 올려본적이 없어서 직접 확인해본건 아니지만..

**Comment by DolphaGo** [comment]
인스타 피드에 본인이 작성한 글도 보입니다.

**Comment by sangdo913** [comment]
아맞다.. 제가 글을 잘 안올리네요. 글이 보일리가 없네
감사합니다.
