### ISSUE TITLE
signup에 관한 질문

### ISSUE THREAD

**Issue by AndoneKwon** [INSPJT/instagram_clone_backend#129]
# Question
- 1. signUpReqDto를 UsernamePasswordAuthenticationToken이라는 객체로 변환시켜주던데 찾아보니까 principal이 유저의 아이디값이고 credentials가 비밀번호라고 하는거 같은데 맞나요??
- 2. 만약 그렇다면 authenticationManagerBuilder.getObject().authenticate(authenticationToken); 이 부분에서 사용자의 비밀번호를 체크한다고 주석으로 설명을 달아주셨는데 DB를 찾는 로직울 loadUserByUsername 로 실행한다고 하는데 설정은 어느곳에서 하는것인가요..?
- 3. SecurityUtil 클래스 안에 getCurrentMemberId를 보면.. authentication.getName이라는 함수로 유저의 Id값을 받아오는것 같은데 이 설정은 Default인가요??

감사합니다..

**Comment by ParkJiwoon** [comment]
1. 예 맞습니다.
2. 스프링 시큐리티 내부적으로 처리해줍니다. [블로그 포스팅](https://bcp0109.tistory.com/301?category=981824) 에서 `6.3. CustomUserDetailsService` 챕터 보면 내부 코드 따라간게 있습니다.
3. `JwtFilter` 보면 토큰 검증하고 `SecurityContextHolder.getContext().setAuthentication(authentication)` 로 세팅해줍니다

**Comment by AndoneKwon** [comment]
> 1. 예 맞습니다.
> 2. 스프링 시큐리티 내부적으로 처리해줍니다. [블로그 포스팅](https://bcp0109.tistory.com/301?category=981824) 에서 `6.3. CustomUserDetailsService` 챕터 보면 내부 코드 따라간게 있습니다.
> 3. `JwtFilter` 보면 토큰 검증하고 `SecurityContextHolder.getContext().setAuthentication(authentication)` 로 세팅해줍니다

블로그 글을 디테일 하게 찾아보지 못했네요. 앞으로는 더 구체적으로 찾아보고 질문하겠습니다.
자세한 친절한 답변 감사합니다!
