### ISSUE TITLE
Member Entity 의 필드명 변경 및 추가 필요

### ISSUE THREAD

**Issue by ParkJiwoon** [INSPJT/instagram_clone_backend#32]
## ISSUE

1. Member Entity 에 프로필 이미지 URL 이 들어가야 합니다.
2. Profile 테이블을 따로 만들지.. 아니면 그냥 계정 하나당 프로필 하나 정책으로 한 테이블로 갈지도 의논 필요
3. 현재 필드명이 `name`, `nickName` 으로 되어 있는데 인스타를 보니 이메일 외에 "사용자 이름" 으로도 로그인이 가능하네요.
식별 가능한 ID 라고 생각해도 될것같은데 `nickName` 이라는 네이밍은 혼란을 야기할 수 있을것 같습니다.

![image](https://user-images.githubusercontent.com/28972341/110313450-c8841780-8049-11eb-9127-c54d298e62de.png)

**Comment by adamdoha** [comment]
`nickName`, `displayId`

**Comment by ParkJiwoon** [comment]
1. 프로필 이미지는 `profilePictureUrl`
2. 프로필 Table 은 나중에 필요에 의해 나눠도 큰 공수가 없을 것 같음 일단 원테이블 전략으로 함
3. `nickName` 은 `@Nullable`, `displayId` 는 `@NotNull` 로 `Unique`
