### ISSUE TITLE
Https 적용

### ISSUE THREAD

**Issue by DolphaGo** [INSPJT/instagram_clone_backend#47]

**Comment by goodGid** [comment]
AWS Route 53 사용하지 않고
Local에 설치해서 HTTPS 적용하는 방법 !

DNS 설정 : https://goodgid.github.io/Free-Domain/
SSL 인증서 설치 : https://goodgid.github.io/Apply-SSL/
Nginx 적용 : https://goodgid.github.io/Nginx/

**Comment by heonilp** [comment]
1. DNS설정 :  yurivon.ml (http://www.yurivon.ml/swagger-ui.html#)

**Comment by DolphaGo** [comment]
Https 설정 완료되었으므로 close 합니다.
