### ISSUE TITLE
Feed

### ISSUE THREAD

**Issue by DolphaGo** [INSPJT/instagram_clone_backend#52]
# Feature
- Feed

# Goal
- 사용자에 맞도록 게시물을 맞춰서 띄워 줌
- 중복이 없어야함
- 성능 이슈 고려할 것

# Assignees
- @ParkJiwoon 
- @DolphaGo

**Comment by ParkJiwoon** [comment]
성능 때문에 [인프런 김영한님에게 질문](https://www.inflearn.com/questions/178802) 남겼음

**Comment by ParkJiwoon** [comment]
@DolphaGo 

일단 Feed 자체는 작성됐는데 이슈 닫아도 되나요?
QueryDSL 적용은 따로 하는게 나을것같아서요

**Comment by ParkJiwoon** [comment]
Dto 변환도 좀 수정해야되긴 합니다.
`post.getCommentLikes().size()` 같은거 호출할 때 count 쿼리가 아니라 그냥 조회 쿼리가 날라가더라구요.
이거 `post` 테이블 내에 `commentsLikeCount` 라는 컬럼을 하나 추가하던지 카운트 쿼리를 직접 날리게 해야 할거같아요.
아니면 Collections 의 size 호출할 때 count 쿼리로 날라가게 하는 JPA 옵션이 있나요?

**Comment by DolphaGo** [comment]
> @DolphaGo
> 
> 일단 Feed 자체는 작성됐는데 이슈 닫아도 되나요?
> QueryDSL 적용은 따로 하는게 나을것같아서요

네



> Dto 변환도 좀 수정해야되긴 합니다.
> `post.getCommentLikes().size()` 같은거 호출할 때 count 쿼리가 아니라 그냥 조회 쿼리가 날라가더라구요.
> 이거 `post` 테이블 내에 `commentsLikeCount` 라는 컬럼을 하나 추가하던지 카운트 쿼리를 직접 날리게 해야 할거같아요.
> 아니면 Collections 의 size 호출할 때 count 쿼리로 날라가게 하는 JPA 옵션이 있나요?

말씀하신 해당 코드에서의 조회쿼리 날라가는 이슈는
```
post.getCommentLikes().size()
```
컬렉션이 초기화가 되지 않은 상태에서 개수를 세려니 조회쿼리가 날라가는 것일텐데요.
컬렉션 초기화 후 size()를 하면 JAVA 컬렉션 내의 객체 개수를 가져올텐데요.

**Comment by ParkJiwoon** [comment]
**슬랙 대화내용 정리**

일단 실수한게 `getCommentLikes()` 가 아니라 아래 두 메서드입니다.
```java
.likeCount(post.getPostLikes().size())
.commentCount(post.getComments().size())
```

<br>

`postLikes` 와 `comments` 는 각각 좋아요 누른 사람들 데이터와 게시글 데이터를 의미합니다.
따라서 인스타 피드를 내려주는 시점에서는 알 필요가 없습니다.

1. repository 에서 count 만 조회하는 메서드로 호출
2. `post` 테이블 컬럼으로 `likeCount` 와 `commentSize` (예명) 를 추가해서 갯수만 따로 관리

두 가지 방법이 있으며 @DolphaGo 와 얘기해서 2 번 방향으로 결정

**Comment by ParkJiwoon** [comment]
Feed API 는 개발 완료되었으므로 이슈 종료합니다.
추가적인 수정사항은 새로운 이슈 따서 진행
