### ISSUE TITLE
대댓글 로딩관련 이슈

### ISSUE THREAD

**Issue by haeunkim428** [INSPJT/instagram_clone_backend#57]
# Feature
- 대댓글 많을 때 한번에 3개만 보여주고, 한번 누를 때마다 3개씩 더 보여줌
  (3개보다 적게 남으면 남은만큼)
- 가져온 것들은 숨겼다가 다시 열면 다 보여줌
- "많을 때"의 기준 정한 거 있으신가요?
- 백에서 어떤식으로 던져주시는지 정해진 거 있나요?

# Goal
- 

# Assignees
- 관련 담당자 어사인 부탁드립니다

**Comment by ParkJiwoon** [comment]
많을 때 기준은 따로 정한거 없고 무조건 엄청 많다고 가정하고 5개 ~ 10개 정도만 던져줄 겁니다.
더보기 누르면서 다음 데이터 필요한 시점에 마지막 대댓글 ID 넘겨준다고 생각하면 될거같아요

**Comment by DolphaGo** [comment]
5~10개도 너무 많네요. 3개만 보여드리겠습니다.
@haeunkim428 요런 안건은 Question Template 이용하시면 될 것 같아요.

**Comment by haeunkim428** [comment]
댓글도 같은 이슈 있습니다
인스타그램에서 댓글은 10개씩 던져주는데 10개로 진행하면 될까요?

**Comment by DolphaGo** [comment]
> 댓글도 같은 이슈 있습니다
> 인스타그램에서 댓글은 10개씩 던져주는데 10개로 진행하면 될까요?

댓글 3, 대댓글 3으로 드릴게요

**Comment by haeunkim428** [comment]
실제에서는 아래와 같은데 실제랑 맞춰갈까요?

피드 -> 댓글 2개
댓글창 -> 댓글 12개(초기값, 더보기 버튼 누를 때마다)
대댓글창 -> 대댓글 3개(초기값, 더보기 버튼 누를 때마다)

**Comment by ParkJiwoon** [comment]
> 실제에서는 아래와 같은데 실제랑 맞춰갈까요?
> 
> 피드 -> 댓글 2개
> 댓글창 -> 댓글 12개(초기값, 더보기 버튼 누를 때마다)
> 대댓글창 -> 대댓글 3개(초기값, 더보기 버튼 누를 때마다)

네 그렇게 진행할게요

**Comment by ParkJiwoon** [comment]
궁금증은 해결된 것 같아 이슈 종료합니다.
나중에 나오는 API 문서를 확인해주시면 됩니다.
