### ISSUE TITLE
댓글 api 형식

### ISSUE THREAD

**Issue by haeunkim428** [INSPJT/instagram_clone_backend#58]
# Feature
- aos, ios 분들께서는 프론트&백엔드 협의 내용 따른다고 하십니다
- GET Comment api 요구 형식
```
[
	{
		"id": "number",
		"content": "string",
		"author": "Member",
		"isLike": "Boolean",
		"likeLength": "number",
		"replyLength": "number",
		"created": "number", // year/month/day/time -> millisecond
		"received": "number"
	}
]
```
- 위 User 타입은 백엔드에서 기존에 만들어놓은 아래 형식을 의미합니다
```
{
	"displayId": "string",
	"email": "string",
	"nickname": "string",
	"profileImageUrl": "string"
}
```

# Goal
- 백엔드와 api 협의완료 후 aos ios에 공유

# Assignees
- @DolphaGo

**Comment by ParkJiwoon** [comment]
@haeunkim428 

1. `replyContent` 는 필요 없나요? 
인스타 보면 대댓글로 하나 나와있고 답글 ~개 더보기 이런 형식도 있던데  필요하지 않을까 싶어서요.

2. ~User~ 말구 Member 타입을 사용합니다
댓글에서는 `displayId` 와 `profileImageUrl` 두개만 있어도 되지 않을까요?
다른 사람의 `email` 은 노출되지도 않고 `nickname` 도 그 사람의 프로필을 조회할 때 내려주면 되니까 불필요한 정보라고 생각됩니다.

**Comment by haeunkim428** [comment]
1. 해당 상황(대댓글이 누르지 않았는데도 보이는 경우)이 어떤 기준으로 일어나는 상황인지를 파악하지를 못해서 
-> 대댓글은 피드 볼 때 노출하지 않기로 프론트에서 합의했습니다!
(대부분의 경우에는 댓글만 미리 보기로 보임)

2. 넵! Member 타입 맞습니다, 해당 내용에 동의합니다! 백엔드 편의 상 Member 타입 하나로 처리하시는게 좋을거 같아 저렇게 제안드렸습니다
-> Member 에서 displayId, profileImageUrl로 변경하는게 나을까요?

**Comment by ParkJiwoon** [comment]
1. 알겠습니다
2. 굳이 변경안해도 될것같네요

**Comment by haeunkim428** [comment]
넵 그럼 백엔드에서 위 이슈 합의되거나 수정사항 있으면 알려주세요! :)
일단은 저렇게 진행하고 있겠습니다!

**Comment by haeunkim428** [comment]
추가되어야할 사항이 있습니다
몇 번째 댓글까지 불러와졌는지를 클라 단에서 api 요청할 때 같이 담아서 보내야
그 이후로 몇 개씩 댓글을 보내주실 수 있을거 같습니다

api에 recieved라는 필드 number type으로 추가하겠습니다

**Comment by ParkJiwoon** [comment]
> api에 `received`라는 필드 `number` type으로 추가하겠습니다

다음 요청할 때 마지막으로 받은 댓글 `id` 를 파라미터로 넣어주면 됩니다.

아직 댓글쪽은 구현 안되어 있는 것 같은데 [GET /members/{displayId}/posts](https://yurivon.ml/swagger-ui.html#!/profile-controller/getPostsUsingGET) 처럼 나중에 수정할 예정입니다.

cc. @DolphaGo

**Comment by haeunkim428** [comment]
처음 요청할 때는 어떤 값 담아보내면 될까요?

**Comment by ParkJiwoon** [comment]
> 처음 요청할 때는 어떤 값 담아보내면 될까요?

파라미터 값이 optional 이라 처음에는 값을 안주셔도 될겁니다

**Comment by haeunkim428** [comment]
comment modify api 도 추가 부탁드립니다~

**Comment by DolphaGo** [comment]
@haeunkim428 지운님과 대화결과를 바탕으로 author에서 email은 제외하겠습니다.

{
	"displayId": "string",
	"nickname": "string",
	"profileImageUrl": "string"
}

**Comment by haeunkim428** [comment]
확인했습니다!

**Comment by haeunkim428** [comment]
displayId랑 nickname이 피드 프로필에서 보면 다른 부분으로 나뉘는데
제 피드 가서 보면 '하은'이라고 되어있는 부분이 해당 nickname입니다
(displayId와 별개의 것이에요! 실제 인스타에서는 "사용자 이름"이라는 이름으로 취급되고 있습니다)

**Comment by haeunkim428** [comment]
Boolean isFollowedByMe; 필요합니다!
피드에만 추가해두고 댓글에서는 누락했네요ㅜㅜ
추가해주시면 감사하겠습니다

**Comment by DolphaGo** [comment]
음, 제가 그 부분을 잘 몰라서 보여지는 쪽은 프론트쪽에서 해주시겠죠? ㅎㅎ

    String displayId;
    String nickname; 
    String profileImageUrl;
    Boolean isFollowedByMe;

author는 이렇게 할게요.

**Comment by haeunkim428** [comment]
확인했습니다 :) 👍
