### ISSUE TITLE
배포 시 Master 태그 관리 

### ISSUE THREAD

**Issue by DolphaGo** [INSPJT/instagram_clone_backend#95]
# Feature
- Master branch tag 생성

# Goal
- Production 버전 관리
- 깃 플로우 전략

# Assignees
- @heonilp

**Comment by heonilp** [comment]
1일차 Production 버전 관리 방법 실습
2021-05-07 github action 배포할때 tag 참고

1. github action 태그 ci 날짜로 남기는 법 예제
https://stackoverflow.com/questions/60963759/use-github-actions-to-create-a-tag-but-not-a-release
https://github.com/tvdias/github-tagger

2. github action 태그 ci 버전으로 남기는 법 예제
https://github.com/marketplace/actions/github-tag

3. 제대로 남겨지나 github action ci 실습 - tag 성공시 버전으로 남겨짐 
  https://colorscripter.com/s/E0cHmIt

4.하지만, build실패시 tag가 따로 돌아서 실패해도 tag가 남겨지기 때문에 build에 넣어야함  
https://colorscripter.com/s/3xWVm1D

2일차 깃플로우 전략 생각해보기 및 정리 할 예정.

**Comment by goodGid** [comment]
와우 !!!
